name: Python CI

on:
  push:
    branches:
      - jagadish1296-st
      - list_string_functions.py
      - test_list_functions.py
  pull_request:
    branches:
      - jagadish1296-st
      - list_string_functions.py
      - test_list_functions.py

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Verify directory structure
      run: |
        echo "Listing files in root directory:"
        ls -R  # Lists all files and directories in the repository
        echo "Listing files in tests directory:"
        ls tests || echo "No 'tests' directory found"

    - name: Run tests
      run: |
        pytest tests -v

